### ISSUE TITLE
building with cmake-3.20.6 the libgtest and libgtest_main left off link command

### ISSUE THREAD

**Issue by billpriest** [dadep88/RLSFilter#1]
Building on Ubuntu 21.10 with cmake 3.20.6 and gcc-10.3 for some reason the libgtest and libgtest_main were left off the link command when building the unit test.  After adding them manually the resulting executable ran w/o error.
I downloaded the latest and greatest google-test/mock from github and checked out release-1.11.0.
Changing to produced an executable which ran successfully with make test
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index ce34c30..74f34f1 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -10,8 +10,8 @@ add_executable("${PROJECT_NAME}_test" ${test_sources})
 target_include_directories("${PROJECT_NAME}_test" PRIVATE include)
 
 #Link test executable against gtest &gtest_main
-target_link_libraries("${PROJECT_NAME}_test" ${GTEST_LIBRARY} ${GTEST_MAIN_LIBRARY})
+target_link_libraries("${PROJECT_NAME}_test" ${GTEST_BOTH_LIBRARIES})
 target_link_libraries("${PROJECT_NAME}_test" ${CMAKE_PROJECT_NAME})
 target_link_libraries( "${PROJECT_NAME}_test" pthread)

**Comment by dadep88** [comment]
@billpriest Thanks for the proper suggestion
